name: DAST Security Scan

on:
  workflow_dispatch:
  
permissions:
  contents: read
  issues: write

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fix permissions for ZAP
        run: |
          chmod -R 777 .

      - name: OWASP ZAP Automation Scan
        # uses: zaproxy/action-baseline@v0.15.0
        # uses: zaproxy/action-full-scan@v0.10.0
        uses: zaproxy/action-automation@v0.5.0
        with:
          target: 'https://juice-shop.herokuapp.com/'
          plan: zap.yaml
          cmd_options: >
            -m 5
            -r zap_scan_report.html
            -w zap_scan_report.md
            -J zap_scan_report.json
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files after ZAP scan
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_report
          path: |
            zap_scan_report.*
